### ISSUE TITLE
NullPointerException aparece aleatoriamente ao dar run na main

### ISSUE THREAD

**Issue by dandavid9** [bruno-esgts/product-search-lib#1]
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "pt.brunojesus.productsearch.sources.pingodoce.model.PingoDoceSearchResponse.getSections()" because the return value of "pt.brunojesus.productsearch.sources.pingodoce.http.PingoDoceClient.search(String, int, int)" is null
	at pt.brunojesus.productsearch.sources.pingodoce.PingoDoce.search(PingoDoce.java:47)
	at pt.brunojesus.productsearch.api.ProductSearch.search(ProductSearch.java:52)
	at pt.tpsi.festa.comesebebes.ComesEBebes.adicionarProduto(ComesEBebes.java:62)
	at pt.tpsi.festa.comesebebes.ComesEBebes.adicionarProduto(ComesEBebes.java:73)
	at pt.tpsi.festa.comesebebes.Main.main(Main.java:10)

**Comment by bruno-esgts** [comment]
Em vez da NullPointerException deves passar a receber uma `ProductFetchException` no caso de existir um erro ao obter os produtos da loja.
